name: 'Docker Build'

on:
    workflow_dispatch:
    release:
        types: [released]

jobs:
    # act -j build -W ./.github/workflows/build.yaml --secret-file  .dockerhub.secrets
    build:
        strategy:
            matrix:
                server: [ fpm, apache ]
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Build
              uses: docker/build-push-action@v4
              with:
                  context: .
                  build-args: |
                      TIMEZONE=Europe/London
                      BASE=${{ matrix.server }}
                  platforms: linux/amd64,linux/arm64 #,linux/arm/v8,linux/arm/v7,linux/arm/v6
                  tags: |
                      tobybatch/kimai-base:${{ matrix.server }}
                  push: true


